### ISSUE TITLE
Need to install 'requests' lib first

### ISSUE THREAD

**Issue by cmillecan** [holbertonschool/W3C-Validator#4]
It looks like this script depends on the `requests` lib, which the instructions don't mention. Might be helpful for folks to know that they first will need to download that lib first (i.e.`pip3 install requests`)

![image](https://user-images.githubusercontent.com/26477928/87237122-13f50180-c3a7-11ea-83f5-be9ba15e0f23.png)

**Comment by jmmarco** [comment]
Fixed and updated some features. Thanks for reporting this @cmillecan 👍
